"""Initial migration

Revision ID: 6a0685835bf0
Revises: 
Create Date: 2022-06-17 22:09:14.346971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0685835bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chartdata_id'), 'chartdata', ['id'], unique=False)
    op.create_index(op.f('ix_sprockets_id'), 'sprockets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprockets_id'), table_name='sprockets')
    op.drop_index(op.f('ix_chartdata_id'), table_name='chartdata')
    # ### end Alembic commands ###
